-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Хост: localhost
-- Время создания: Май 08 2014 г., 11:50
-- Версия сервера: 5.5.16
-- Версия PHP: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- База данных: `my_moneygun`
--

-- --------------------------------------------------------

--
-- Структура таблицы `wp_commentmeta`
--

CREATE TABLE IF NOT EXISTS `wp_commentmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`meta_id`),
  KEY `comment_id` (`comment_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

-- --------------------------------------------------------

--
-- Структура таблицы `wp_comments`
--

CREATE TABLE IF NOT EXISTS `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT '0',
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT '',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID` (`comment_post_ID`),
  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),
  KEY `comment_date_gmt` (`comment_date_gmt`),
  KEY `comment_parent` (`comment_parent`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

-- --------------------------------------------------------

--
-- Структура таблицы `wp_huge_itslider_images`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_images` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `slider_id` varchar(200) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `sl_url` varchar(128) DEFAULT NULL,
  `sl_type` text NOT NULL,
  `link_target` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` tinyint(4) unsigned DEFAULT NULL,
  `published_in_sl_width` tinyint(4) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

--
-- Дамп данных таблицы `wp_huge_itslider_images`
--

INSERT INTO `wp_huge_itslider_images` (`id`, `name`, `slider_id`, `description`, `image_url`, `sl_url`, `sl_type`, `link_target`, `ordering`, `published`, `published_in_sl_width`) VALUES
(1, '', '1', '', 'http://moneygun.altervista.org/wp-content/plugins/slider-image/Front_images/slides/slide1.jpg', 'http://huge-it.com', 'image', '_blank', 1, 1, NULL),
(2, 'Simple Usage', '1', '', 'http://moneygun.altervista.org/wp-content/plugins/slider-image/Front_images/slides/slide2.jpg', 'http://huge-it.com', 'image', '_blank', 2, 1, NULL),
(3, 'Huge-IT Slider', '1', 'The slider allows having unlimited amount of images with their titles and descriptions. The slider uses autogenerated shortcodes making it easier for the users to add it to the custom location.', 'http://moneygun.altervista.org/wp-content/plugins/slider-image/Front_images/slides/slide3.jpg', 'http://huge-it.com', 'image', '_blank', 3, 1, NULL);

-- --------------------------------------------------------

--
-- Структура таблицы `wp_huge_itslider_params`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_params` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `title` varchar(200) CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `value` varchar(200) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=123 ;

--
-- Дамп данных таблицы `wp_huge_itslider_params`
--

INSERT INTO `wp_huge_itslider_params` (`id`, `name`, `title`, `description`, `value`) VALUES
(89, 'slider_crop_image', 'Slider crop image', 'Slider crop image', 'resize'),
(90, 'slider_title_color', 'Slider title color', 'Slider title color', 'ffffff'),
(91, 'slider_title_font_size', 'Slider title font size', 'Slider title font size', '14'),
(92, 'slider_description_color', 'Slider description color', 'Slider description color', 'ffffff'),
(93, 'slider_description_font_size', 'Slider description font size', 'Slider description font size', '13'),
(94, 'slider_title_position', 'Slider title position', 'Slider title position', 'right-top'),
(95, 'slider_description_position', 'Slider description position', 'Slider description position', 'right-bottom'),
(96, 'slider_title_border_size', 'Slider Title border size', 'Slider Title border size', '0'),
(97, 'slider_title_border_color', 'Slider title border color', 'Slider title border color', 'ffffff'),
(98, 'slider_title_border_radius', 'Slider title border radius', 'Slider title border radius', '5'),
(99, 'slider_description_border_size', 'Slider description border size', 'Slider description border size', '0'),
(100, 'slider_description_border_color', 'Slider description border color', 'Slider description border color', 'ffffff'),
(101, 'slider_description_border_radius', 'Slider description border radius', 'Slider description border radius', '5'),
(102, 'slider_slideshow_border_size', 'Slider slideshow border size', 'Slider slideshow border size', '0'),
(103, 'slider_slideshow_border_color', 'Slider slideshow border color', 'Slider slideshow border color', 'ffffff'),
(104, 'slider_slideshow_border_radius', 'Slider slideshow border radius', 'Slider slideshow border radius', '0'),
(105, 'slider_navigation_type', 'Slider navigation type', 'Slider navigation type', '1'),
(106, 'slider_navigation_position', 'Slider navigation position', 'Slider navigation position', 'bottom'),
(107, 'slider_title_background_color', 'Slider title background color', 'Slider title background color', '000000'),
(108, 'slider_description_background_color', 'Slider description background color', 'Slider description background color', '000000'),
(109, 'slider_title_transparent', 'Slider title has background', 'Slider title has background', 'checked'),
(110, 'slider_description_transparent', 'Slider description has background', 'Slider description has background', 'checked'),
(111, 'slider_slider_background_color', 'Slider slider background color', 'Slider slider background color', 'ffffff'),
(112, 'slider_dots_position', 'slider dots position', 'slider dots position', 'top'),
(113, 'slider_active_dot_color', 'slider active dot color', '', 'ffffff'),
(114, 'slider_dots_color', 'slider dots color', '', '000000'),
(115, 'slider_description_width', 'Slider description width', 'Slider description width', '50'),
(116, 'slider_description_height', 'Slider description height', 'Slider description height', '40'),
(117, 'slider_description_background_transparency', 'slider description background transparency', 'slider description background transparency', '1'),
(118, 'slider_description_text_align', 'description text-align', 'description text-align', 'left'),
(119, 'slider_title_width', 'slider title width', 'slider title width', '100'),
(120, 'slider_title_height', 'slider title height', 'slider title height', '100'),
(121, 'slider_title_background_transparency', 'slider title background transparency', 'slider title background transparency', '1'),
(122, 'slider_title_text_align', 'title text-align', 'title text-align', 'left');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_huge_itslider_sliders`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_sliders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `sl_height` int(11) unsigned DEFAULT NULL,
  `sl_width` int(11) unsigned DEFAULT NULL,
  `pause_on_hover` text,
  `slider_list_effects_s` text,
  `description` text,
  `param` text,
  `ordering` int(11) NOT NULL,
  `published` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- Дамп данных таблицы `wp_huge_itslider_sliders`
--

INSERT INTO `wp_huge_itslider_sliders` (`id`, `name`, `sl_height`, `sl_width`, `pause_on_hover`, `slider_list_effects_s`, `description`, `param`, `ordering`, `published`) VALUES
(1, 'My First Slider', 375, 600, 'on', 'random', '4000', '700', 1, '300');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_links`
--

CREATE TABLE IF NOT EXISTS `wp_links` (
  `link_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `link_url` varchar(255) NOT NULL DEFAULT '',
  `link_name` varchar(255) NOT NULL DEFAULT '',
  `link_image` varchar(255) NOT NULL DEFAULT '',
  `link_target` varchar(25) NOT NULL DEFAULT '',
  `link_description` varchar(255) NOT NULL DEFAULT '',
  `link_visible` varchar(20) NOT NULL DEFAULT 'Y',
  `link_owner` bigint(20) unsigned NOT NULL DEFAULT '1',
  `link_rating` int(11) NOT NULL DEFAULT '0',
  `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `link_rel` varchar(255) NOT NULL DEFAULT '',
  `link_notes` mediumtext NOT NULL,
  `link_rss` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`link_id`),
  KEY `link_visible` (`link_visible`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Структура таблицы `wp_options`
--

CREATE TABLE IF NOT EXISTS `wp_options` (
  `option_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `option_name` varchar(64) NOT NULL DEFAULT '',
  `option_value` longtext NOT NULL,
  `autoload` varchar(20) NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`option_id`),
  UNIQUE KEY `option_name` (`option_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=380 ;

--
-- Дамп данных таблицы `wp_options`
--

INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(1, 'siteurl', 'http://localhost/', 'yes'),
(2, 'blogname', 'FDT STUDIO', 'yes'),
(3, 'blogdescription', 'Future Development Technology', 'yes'),
(4, 'users_can_register', '0', 'yes'),
(5, 'admin_email', 'dimonze@gmail.com', 'yes'),
(6, 'start_of_week', '1', 'yes'),
(7, 'use_balanceTags', '0', 'yes'),
(8, 'use_smilies', '1', 'yes'),
(9, 'require_name_email', '', 'yes'),
(10, 'comments_notify', '', 'yes'),
(11, 'posts_per_rss', '10', 'yes'),
(12, 'rss_use_excerpt', '0', 'yes'),
(13, 'mailserver_url', 'mail.example.com', 'yes'),
(14, 'mailserver_login', 'login@example.com', 'yes'),
(15, 'mailserver_pass', 'password', 'yes'),
(16, 'mailserver_port', '110', 'yes'),
(17, 'default_category', '1', 'yes'),
(18, 'default_comment_status', 'closed', 'yes'),
(19, 'default_ping_status', 'closed', 'yes'),
(20, 'default_pingback_flag', '', 'yes'),
(21, 'posts_per_page', '10', 'yes'),
(22, 'date_format', 'd.m.Y', 'yes'),
(23, 'time_format', 'H:i', 'yes'),
(24, 'links_updated_date_format', 'd.m.Y H:i', 'yes'),
(28, 'comment_moderation', '', 'yes'),
(29, 'moderation_notify', '', 'yes'),
(30, 'permalink_structure', '/%postname%/', 'yes'),
(31, 'gzipcompression', '0', 'yes'),
(32, 'hack_file', '0', 'yes'),
(33, 'blog_charset', 'UTF-8', 'yes'),
(34, 'moderation_keys', '', 'no'),
(35, 'active_plugins', 'a:1:{i:0;s:19:"vslider/vslider.php";}', 'yes'),
(36, 'home', 'http://localhost', 'yes'),
(37, 'category_base', '', 'yes'),
(38, 'ping_sites', 'http://rpc.pingomatic.com/', 'yes'),
(39, 'advanced_edit', '0', 'yes'),
(40, 'comment_max_links', '2', 'yes'),
(41, 'gmt_offset', '4', 'yes'),
(42, 'default_email_category', '1', 'yes'),
(43, 'recently_edited', 'a:5:{i:0;s:55:"/membri/moneygun/wp-content/plugins/vslider/vslider.php";i:1;s:93:"/membri/moneygun/wp-content/plugins/multisite-language-switcher/MultisiteLanguageSwitcher.php";i:2;s:57:"/membri/moneygun/wp-content/themes/twentytwelve/style.css";i:3;s:55:"/membri/moneygun/wp-content/plugins/akismet/akismet.php";i:4;s:59:"/membri/moneygun/wp-content/plugins/slider-image/slider.php";}', 'no'),
(44, 'template', 'default', 'yes'),
(45, 'stylesheet', 'default', 'yes'),
(46, 'comment_whitelist', '', 'yes'),
(47, 'blacklist_keys', '', 'no'),
(48, 'comment_registration', '1', 'yes'),
(49, 'html_type', 'text/html', 'yes'),
(50, 'use_trackback', '0', 'yes'),
(51, 'default_role', 'subscriber', 'yes'),
(52, 'db_version', '27916', 'yes'),
(53, 'uploads_use_yearmonth_folders', '1', 'yes'),
(54, 'upload_path', '', 'yes'),
(55, 'blog_public', '1', 'yes'),
(56, 'default_link_category', '2', 'yes'),
(57, 'show_on_front', 'page', 'yes'),
(58, 'tag_base', '', 'yes'),
(59, 'show_avatars', '1', 'yes'),
(60, 'avatar_rating', 'G', 'yes'),
(61, 'upload_url_path', '', 'yes'),
(62, 'thumbnail_size_w', '150', 'yes'),
(63, 'thumbnail_size_h', '150', 'yes'),
(64, 'thumbnail_crop', '1', 'yes'),
(65, 'medium_size_w', '300', 'yes'),
(66, 'medium_size_h', '300', 'yes'),
(67, 'avatar_default', 'mystery', 'yes'),
(68, 'large_size_w', '1024', 'yes'),
(69, 'large_size_h', '1024', 'yes'),
(70, 'image_default_link_type', 'file', 'yes'),
(71, 'image_default_size', '', 'yes'),
(72, 'image_default_align', '', 'yes'),
(73, 'close_comments_for_old_posts', '', 'yes'),
(74, 'close_comments_days_old', '14', 'yes'),
(75, 'thread_comments', '', 'yes'),
(76, 'thread_comments_depth', '5', 'yes'),
(77, 'page_comments', '', 'yes'),
(78, 'comments_per_page', '50', 'yes'),
(79, 'default_comments_page', 'newest', 'yes'),
(80, 'comment_order', 'asc', 'yes'),
(81, 'sticky_posts', 'a:0:{}', 'yes'),
(82, 'widget_categories', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(83, 'widget_text', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(84, 'widget_rss', 'a:3:{i:1;a:0:{}i:3;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(85, 'uninstall_plugins', 'a:2:{s:17:"wpclef/wpclef.php";a:2:{i:0;s:9:"ClefSetup";i:1;s:16:"uninstall_plugin";}s:57:"multisite-language-switcher/MultisiteLanguageSwitcher.php";a:2:{i:0;s:10:"MslsPlugin";i:1;s:9:"uninstall";}}', 'no'),
(86, 'timezone_string', '', 'yes'),
(87, 'page_for_posts', '0', 'yes'),
(88, 'page_on_front', '12', 'yes'),
(89, 'default_post_format', '0', 'yes'),
(90, 'link_manager_enabled', '0', 'yes'),
(91, 'initial_db_version', '26691', 'yes'),
(92, 'wp_user_roles', 'a:5:{s:13:"administrator";a:2:{s:4:"name";s:13:"Administrator";s:12:"capabilities";a:65:{s:13:"switch_themes";b:1;s:11:"edit_themes";b:1;s:16:"activate_plugins";b:1;s:12:"edit_plugins";b:1;s:10:"edit_users";b:1;s:10:"edit_files";b:1;s:14:"manage_options";b:1;s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:6:"import";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:8:"level_10";b:1;s:7:"level_9";b:1;s:7:"level_8";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;s:12:"delete_users";b:1;s:12:"create_users";b:1;s:17:"unfiltered_upload";b:1;s:14:"edit_dashboard";b:1;s:14:"update_plugins";b:1;s:14:"delete_plugins";b:1;s:15:"install_plugins";b:1;s:13:"update_themes";b:1;s:14:"install_themes";b:1;s:11:"update_core";b:1;s:10:"list_users";b:1;s:12:"remove_users";b:1;s:9:"add_users";b:1;s:13:"promote_users";b:1;s:18:"edit_theme_options";b:1;s:13:"delete_themes";b:1;s:6:"export";b:1;s:17:"xili_language_set";b:1;s:18:"xili_language_menu";b:1;s:23:"xili_language_clone_tax";b:1;}}s:6:"editor";a:2:{s:4:"name";s:6:"Editor";s:12:"capabilities";a:36:{s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;s:18:"xili_language_menu";b:1;s:23:"xili_language_clone_tax";b:1;}}s:6:"author";a:2:{s:4:"name";s:6:"Author";s:12:"capabilities";a:10:{s:12:"upload_files";b:1;s:10:"edit_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:4:"read";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;s:22:"delete_published_posts";b:1;}}s:11:"contributor";a:2:{s:4:"name";s:11:"Contributor";s:12:"capabilities";a:5:{s:10:"edit_posts";b:1;s:4:"read";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;}}s:10:"subscriber";a:2:{s:4:"name";s:10:"Subscriber";s:12:"capabilities";a:2:{s:4:"read";b:1;s:7:"level_0";b:1;}}}', 'yes'),
(93, 'widget_search', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(94, 'widget_recent-posts', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(95, 'widget_recent-comments', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(96, 'widget_archives', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(97, 'widget_meta', 'a:2:{s:12:"_multiwidget";i:1;i:1;a:0:{}}', 'yes'),
(98, 'sidebars_widgets', 'a:5:{s:19:"wp_inactive_widgets";a:1:{i:0;s:5:"rss-3";}s:9:"sidebar-1";a:0:{}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}s:13:"array_version";i:3;}', 'yes'),
(99, 'cron', 'a:6:{i:1399543151;a:1:{s:29:"wp_session_garbage_collection";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:6:"hourly";s:4:"args";a:0:{}s:8:"interval";i:3600;}}}i:1399561920;a:1:{s:20:"wp_maybe_auto_update";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1399583580;a:3:{s:16:"wp_version_check";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:17:"wp_update_plugins";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:16:"wp_update_themes";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1399626803;a:1:{s:19:"wp_scheduled_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1399628426;a:1:{s:30:"wp_scheduled_auto_draft_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}s:7:"version";i:2;}', 'yes'),
(366, 'vslider_options', 'a:48:{s:5:"width";s:3:"630";s:6:"height";s:3:"280";s:3:"spw";s:1:"7";s:3:"sph";s:1:"5";s:5:"delay";s:4:"3000";s:6:"sDelay";s:2:"30";s:7:"opacity";s:3:"0.7";s:10:"titleSpeed";s:4:"1500";s:6:"effect";s:0:"";s:10:"navigation";s:4:"true";s:9:"stickynav";s:5:"false";s:5:"links";s:4:"true";s:7:"buttons";s:4:"true";s:10:"hoverPause";s:4:"true";s:11:"borderWidth";s:1:"5";s:12:"borderRadius";s:1:"0";s:11:"borderColor";s:6:"FFFFFF";s:10:"fontFamily";s:28:"Arial, Helvetica, sans-serif";s:9:"titleFont";s:2:"16";s:8:"fontSize";s:2:"12";s:9:"textColor";s:6:"FFFFFF";s:7:"bgColor";s:6:"222222";s:8:"navstyle";s:4:"none";s:8:"arrstyle";s:4:"none";s:8:"navplace";s:17:"10px 0 10px 100px";s:8:"timthumb";s:1:"1";s:7:"quality";s:2:"80";s:6:"layout";s:13:"stripe-bottom";s:9:"holdermar";s:19:"10px 10px 10px 10px";s:11:"holderfloat";s:4:"none";s:9:"customImg";s:4:"true";s:6:"imgCat";s:1:"0";s:10:"catchimage";s:8:"featured";s:7:"slideNr";s:1:"3";s:7:"excerpt";s:4:"true";s:5:"chars";s:3:"200";s:6:"slide1";s:71:"http://vladtimoshenko.com/wp-content/uploads/2013/02/it-outsourcing.png";s:5:"link1";s:0:"";s:8:"heading1";s:0:"";s:5:"desc1";s:0:"";s:6:"slide2";s:75:"http://moneygun.altervista.org/wp-content/plugins/vslider/images/slide2.jpg";s:5:"link2";s:0:"";s:8:"heading2";s:0:"";s:5:"desc2";s:0:"";s:6:"slide3";s:75:"http://moneygun.altervista.org/wp-content/plugins/vslider/images/slide3.jpg";s:5:"link3";s:0:"";s:8:"heading3";s:0:"";s:5:"desc3";s:0:"";}', 'yes'),
(367, 'vslider_support', '0', 'yes'),
(368, '_site_transient_update_plugins', 'O:8:"stdClass":3:{s:12:"last_checked";i:1399542128;s:8:"response";a:0:{}s:12:"translations";a:0:{}}', 'yes'),
(371, 'widget_vslider-widget', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(372, 'mainslider', 'a:41:{s:5:"width";s:3:"935";s:6:"height";s:3:"375";s:3:"spw";s:1:"7";s:3:"sph";s:1:"5";s:5:"delay";s:4:"3000";s:6:"sDelay";s:2:"30";s:7:"opacity";s:3:"0.7";s:10:"titleSpeed";s:4:"1500";s:6:"effect";s:0:"";s:10:"navigation";s:5:"false";s:9:"stickynav";s:5:"false";s:5:"links";s:4:"true";s:7:"buttons";s:4:"true";s:10:"hoverPause";s:4:"true";s:11:"borderWidth";s:1:"5";s:12:"borderRadius";s:1:"0";s:11:"borderColor";s:6:"FFFFFF";s:10:"fontFamily";s:28:"Arial, Helvetica, sans-serif";s:9:"titleFont";s:2:"16";s:8:"fontSize";s:2:"12";s:9:"textColor";s:6:"FFFFFF";s:7:"bgColor";s:6:"222222";s:8:"navstyle";s:4:"none";s:8:"arrstyle";s:4:"none";s:8:"navplace";s:17:"10px 0 10px 100px";s:8:"timthumb";s:1:"1";s:7:"quality";s:2:"80";s:6:"layout";s:13:"stripe-bottom";s:9:"holdermar";s:19:"10px 10px 10px 10px";s:11:"holderfloat";s:4:"none";s:9:"customImg";s:4:"true";s:6:"target";s:6:"_blank";s:6:"imgCat";s:1:"0";s:10:"catchimage";s:5:"first";s:7:"slideNr";s:1:"1";s:7:"excerpt";s:4:"true";s:5:"chars";s:3:"200";s:6:"slide1";s:94:"http://moneygun.altervista.org/wp-content/uploads/2014/05/banner_homepage_ownteam-1024x300.jpg";s:5:"link1";s:0:"";s:8:"heading1";s:0:"";s:5:"desc1";s:0:"";}', 'yes'),
(378, '_transient_is_multi_author', '0', 'yes'),
(299, '_transient_all_the_cool_cats', '0', 'yes'),
(302, '_site_transient_timeout_browser_cdd9bb9381c4c4ef67c3954a553de46b', '1400055392', 'yes'),
(303, '_site_transient_browser_cdd9bb9381c4c4ef67c3954a553de46b', 'a:9:{s:8:"platform";s:7:"Windows";s:4:"name";s:6:"Chrome";s:7:"version";s:13:"34.0.1847.131";s:10:"update_url";s:28:"http://www.google.com/chrome";s:7:"img_src";s:49:"http://s.wordpress.org/images/browsers/chrome.png";s:11:"img_src_ssl";s:48:"https://wordpress.org/images/browsers/chrome.png";s:15:"current_version";s:2:"18";s:7:"upgrade";b:0;s:8:"insecure";b:0;}', 'yes'),
(125, 'recently_activated', 'a:6:{s:57:"multisite-language-switcher/MultisiteLanguageSwitcher.php";i:1399465421;s:41:"responsive-add-ons/responsive-add-ons.php";i:1399453467;s:37:"foobox-image-lightbox/foobox-free.php";i:1399453465;s:37:"disable-comments/disable-comments.php";i:1399453462;s:17:"wpclef/wpclef.php";i:1399453460;s:23:"slider-image/slider.php";i:1399452872;}', 'yes'),
(129, '_transient_twentyfourteen_category_count', '1', 'yes'),
(131, 'current_theme', 'Default', 'yes'),
(132, 'theme_mods_twentytwelve', 'a:10:{i:0;b:0;s:16:"header_textcolor";s:6:"757575";s:16:"background_color";s:6:"bababa";s:16:"background_image";s:0:"";s:17:"background_repeat";s:6:"repeat";s:21:"background_position_x";s:4:"left";s:21:"background_attachment";s:5:"fixed";s:18:"nav_menu_locations";a:1:{s:7:"primary";i:2;}s:16:"sidebars_widgets";a:2:{s:4:"time";i:1399456322;s:4:"data";a:4:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:0:{}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}}}s:12:"header_image";s:13:"remove-header";}', 'yes'),
(133, 'theme_switched', '', 'yes'),
(139, '_transient_random_seed', '6b2bf9684d3a719db1d566c7ab8179ae', 'yes'),
(151, 'nav_menu_options', 'a:2:{i:0;b:0;s:8:"auto_add";a:0:{}}', 'yes'),
(358, 'xili_language_settings', 'a:41:{s:8:"taxonomy";s:8:"language";s:7:"version";s:4:"2.11";s:6:"reqtag";s:4:"lang";s:13:"browseroption";s:0:"";s:19:"authorbrowseroption";s:0:"";s:14:"taxolangsgroup";s:15:"languages_group";s:16:"functions_enable";s:0:"";s:12:"langs_folder";s:10:"/languages";s:12:"theme_domain";s:7:"default";s:8:"homelang";s:0:"";s:17:"langs_list_status";s:3:"set";s:11:"in_nav_menu";s:0:"";s:16:"page_in_nav_menu";s:0:"";s:22:"page_in_nav_menu_array";s:0:"";s:21:"args_page_in_nav_menu";s:0:"";s:24:"multilingual_custom_post";a:0:{}s:19:"langs_in_root_theme";s:0:"";s:7:"domains";a:3:{s:7:"default";s:7:"disable";s:7:"bbpress";s:7:"disable";s:17:"xili_xl_bbp_addon";s:7:"disable";}s:6:"widget";s:6:"enable";s:15:"delete_settings";s:0:"";s:18:"allcategories_lang";s:7:"browser";s:13:"lang_features";a:2:{s:5:"en_us";a:2:{s:7:"charset";s:0:"";s:6:"hidden";s:0:"";}s:5:"ru_ru";a:2:{s:7:"charset";s:0:"";s:6:"hidden";s:0:"";}}s:18:"home_item_nav_menu";s:0:"";s:14:"lang_undefined";s:1:".";s:20:"lang_neither_browser";s:0:"";s:9:"wp_locale";s:9:"wp_locale";s:15:"available_langs";a:2:{i:0;s:1:"4";i:1;s:1:"5";}s:17:"creation_redirect";s:8:"redirect";s:17:"external_xl_style";s:2:"on";s:18:"nav_menu_separator";s:1:"|";s:12:"pforp_select";s:6:"select";s:18:"shortqv_slug_array";a:0:{}s:23:"list_pages_check_option";s:4:"fixe";s:15:"list_link_title";a:4:{s:13:"post_selected";s:20:"Posts selected in %s";s:12:"current_post";s:18:"Current post in %s";s:12:"latest_posts";s:18:"Latest posts in %s";s:14:"view_all_posts";s:20:"View all posts in %s";}s:23:"mo_parent_child_merging";b:0;s:19:"parent_langs_folder";s:0:"";s:21:"enable_fc_theme_class";s:6:"enable";s:17:"theme_alias_cache";a:0:{}s:14:"languages_list";a:2:{i:0;O:8:"stdClass":10:{s:7:"term_id";s:1:"4";s:4:"name";s:5:"en_US";s:4:"slug";s:5:"en_us";s:10:"term_group";s:1:"0";s:16:"term_taxonomy_id";s:1:"4";s:11:"description";s:7:"english";s:6:"parent";s:1:"0";s:5:"count";s:1:"0";s:8:"taxonomy";s:8:"language";s:10:"term_order";s:1:"0";}i:1;O:8:"stdClass":10:{s:7:"term_id";s:1:"5";s:4:"name";s:5:"ru_RU";s:4:"slug";s:5:"ru_ru";s:10:"term_group";s:1:"0";s:16:"term_taxonomy_id";s:1:"5";s:11:"description";s:7:"Russian";s:6:"parent";s:1:"0";s:5:"count";s:1:"0";s:8:"taxonomy";s:8:"language";s:10:"term_order";s:1:"0";}}s:15:"langs_ids_array";a:2:{s:5:"en_us";s:1:"4";s:5:"ru_ru";s:1:"5";}s:24:"show_page_on_front_array";a:2:{s:5:"en_us";s:2:"12";s:5:"ru_ru";s:2:"12";}}', 'yes'),
(168, 'theme_mods_bizflare', 'a:7:{i:0;b:0;s:16:"background_color";s:6:"ebeef1";s:16:"background_image";s:80:"http://localhost/WP/wp-content/themes/bizflare/skins/images/BizFlare/page_bg.png";s:17:"background_repeat";s:6:"repeat";s:21:"background_position_x";s:4:"left";s:21:"background_attachment";s:5:"fixed";s:18:"nav_menu_locations";a:1:{s:7:"primary";i:2;}}', 'yes'),
(169, 'optionsframework', 'a:2:{s:2:"id";s:5:"esell";s:12:"knownoptions";a:3:{i:0;s:8:"BizFlare";i:1;s:6:"BizArk";i:2;s:7:"default";}}', 'yes'),
(170, 'BizFlare', 'a:24:{s:10:"skin_style";s:5:"verve";s:26:"show_featured_image_single";s:5:"false";s:18:"show_rat_on_single";s:4:"true";s:17:"show_pd_on_single";s:4:"true";s:19:"show_cats_on_single";s:4:"true";s:11:"show_np_box";s:4:"true";s:10:"twitter_id";s:0:"";s:8:"redit_id";s:0:"";s:11:"facebook_id";s:0:"";s:10:"stumble_id";s:0:"";s:9:"flickr_id";s:0:"";s:11:"linkedin_id";s:0:"";s:9:"google_id";s:0:"";s:17:"logo_layout_style";s:4:"sbys";s:16:"show_slider_home";s:4:"true";s:18:"show_slider_single";s:5:"false";s:16:"show_slider_page";s:5:"false";s:19:"show_slider_archive";s:5:"false";s:15:"homepage_layout";s:4:"bsix";s:26:"show_BizFlare_quote_bizone";s:4:"true";s:17:"show_bizone_posts";s:4:"true";s:17:"show_posts_bizsix";s:4:"true";s:19:"show_comments_spage";s:4:"true";s:13:"footer_layout";s:3:"one";}', 'yes'),
(331, '_site_transient_timeout_wporg_theme_feature_list', '1399467286', 'yes'),
(332, '_site_transient_wporg_theme_feature_list', 'a:4:{s:6:"Colors";a:15:{i:0;s:5:"black";i:1;s:4:"blue";i:2;s:5:"brown";i:3;s:4:"gray";i:4;s:5:"green";i:5;s:6:"orange";i:6;s:4:"pink";i:7;s:6:"purple";i:8;s:3:"red";i:9;s:6:"silver";i:10;s:3:"tan";i:11;s:5:"white";i:12;s:6:"yellow";i:13;s:4:"dark";i:14;s:5:"light";}s:6:"Layout";a:9:{i:0;s:12:"fixed-layout";i:1;s:12:"fluid-layout";i:2;s:17:"responsive-layout";i:3;s:10:"one-column";i:4;s:11:"two-columns";i:5;s:13:"three-columns";i:6;s:12:"four-columns";i:7;s:12:"left-sidebar";i:8;s:13:"right-sidebar";}s:8:"Features";a:20:{i:0;s:19:"accessibility-ready";i:1;s:8:"blavatar";i:2;s:10:"buddypress";i:3;s:17:"custom-background";i:4;s:13:"custom-colors";i:5;s:13:"custom-header";i:6;s:11:"custom-menu";i:7;s:12:"editor-style";i:8;s:21:"featured-image-header";i:9;s:15:"featured-images";i:10;s:15:"flexible-header";i:11;s:20:"front-page-post-form";i:12;s:19:"full-width-template";i:13;s:12:"microformats";i:14;s:12:"post-formats";i:15;s:20:"rtl-language-support";i:16;s:11:"sticky-post";i:17;s:13:"theme-options";i:18;s:17:"threaded-comments";i:19;s:17:"translation-ready";}s:7:"Subject";a:3:{i:0;s:7:"holiday";i:1;s:13:"photoblogging";i:2;s:8:"seasonal";}}', 'yes'),
(174, 'theme_mods_bizark', 'a:8:{i:0;b:0;s:16:"background_color";s:6:"ebeef1";s:16:"background_image";s:75:"http://localhost/WP/wp-content/themes/bizark/skins/images/verve/page_bg.png";s:17:"background_repeat";s:6:"repeat";s:21:"background_position_x";s:4:"left";s:21:"background_attachment";s:5:"fixed";s:18:"nav_menu_locations";a:1:{s:7:"primary";i:2;}s:16:"sidebars_widgets";a:2:{s:4:"time";i:1396354432;s:4:"data";a:5:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:0:{}s:11:"footer-left";a:0:{}s:13:"footer-center";a:0:{}s:12:"footer-right";N;}}}', 'yes'),
(175, 'BizArk', 'a:65:{s:10:"skin_style";s:5:"verve";s:26:"show_featured_image_single";s:5:"false";s:18:"show_rat_on_single";s:5:"false";s:17:"show_pd_on_single";s:5:"false";s:19:"show_cats_on_single";s:5:"false";s:11:"show_np_box";s:5:"false";s:10:"twitter_id";s:0:"";s:8:"redit_id";s:0:"";s:11:"facebook_id";s:0:"";s:10:"stumble_id";s:0:"";s:9:"flickr_id";s:0:"";s:11:"linkedin_id";s:0:"";s:9:"google_id";s:0:"";s:17:"logo_layout_style";s:7:"onebone";s:16:"show_slider_home";s:4:"true";s:18:"show_slider_single";s:5:"false";s:16:"show_slider_page";s:5:"false";s:19:"show_slider_archive";s:5:"false";s:15:"homepage_layout";s:5:"spage";s:16:"welcome_headline";s:0:"";s:12:"welcome_text";s:0:"";s:18:"left_section_image";s:0:"";s:21:"left_section_headline";s:0:"";s:17:"left_section_text";s:0:"";s:17:"left_section_link";s:0:"";s:20:"center_section_image";s:0:"";s:23:"center_section_headline";s:0:"";s:19:"center_section_text";s:0:"";s:19:"center_section_link";s:0:"";s:19:"right_section_image";s:0:"";s:22:"right_section_headline";s:0:"";s:18:"right_section_text";s:0:"";s:18:"right_section_link";s:0:"";s:24:"show_bizark_quote_bizone";s:4:"true";s:18:"quote_section_text";s:0:"";s:18:"quote_section_name";s:0:"";s:17:"show_bizone_posts";s:4:"true";s:27:"bizeight_left_section_title";s:0:"";s:26:"bizeight_left_section_desc";s:0:"";s:28:"bizeight_left_section_image1";s:0:"";s:28:"bizeight_left_section_title1";s:0:"";s:27:"bizeight_left_section_desc1";s:0:"";s:27:"bizeight_left_section_link1";s:0:"";s:28:"bizeight_left_section_image2";s:0:"";s:28:"bizeight_left_section_title2";s:0:"";s:27:"bizeight_left_section_desc2";s:0:"";s:27:"bizeight_left_section_link2";s:0:"";s:28:"bizeight_left_section_image3";s:0:"";s:28:"bizeight_left_section_title3";s:0:"";s:27:"bizeight_left_section_desc3";s:0:"";s:27:"bizeight_left_section_link3";s:0:"";s:29:"bizeight_middle_section_title";s:0:"";s:25:"bizeight_portfolio_image1";s:0:"";s:25:"bizeight_portfolio_image2";s:0:"";s:25:"bizeight_portfolio_image3";s:0:"";s:25:"bizeight_portfolio_image4";s:0:"";s:25:"bizeight_portfolio_image5";s:0:"";s:25:"bizeight_portfolio_image6";s:0:"";s:25:"bizeight_portfolio_image7";s:0:"";s:25:"bizeight_portfolio_image8";s:0:"";s:28:"bizeight_right_section_title";s:0:"";s:25:"bizeight_news_section_cat";s:1:"1";s:19:"show_posts_bizeight";s:4:"true";s:19:"show_comments_spage";s:5:"false";s:13:"footer_layout";s:3:"two";}', 'yes'),
(176, 'category_children', 'a:0:{}', 'yes'),
(216, 'theme_mods_twentyfourteen', 'a:1:{s:16:"sidebars_widgets";a:2:{s:4:"time";i:1399456330;s:4:"data";a:4:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:0:{}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}}}}', 'yes'),
(217, 'theme_mods_default', 'a:9:{i:0;b:0;s:16:"background_color";s:6:"f2f2f2";s:16:"background_image";s:79:"http://nnm-dhimenes/WP/wp-content/themes/default/skins/images/verve/page_bg.png";s:17:"background_repeat";s:6:"repeat";s:21:"background_position_x";s:4:"left";s:21:"background_attachment";s:5:"fixed";s:18:"nav_menu_locations";a:1:{s:7:"primary";i:2;}s:12:"header_image";s:13:"remove-header";s:16:"header_textcolor";s:6:"515151";}', 'yes'),
(218, 'default', 'a:65:{s:10:"skin_style";s:5:"verve";s:26:"show_featured_image_single";s:5:"false";s:18:"show_rat_on_single";s:4:"true";s:17:"show_pd_on_single";s:4:"true";s:19:"show_cats_on_single";s:4:"true";s:11:"show_np_box";s:4:"true";s:10:"twitter_id";s:0:"";s:8:"redit_id";s:0:"";s:11:"facebook_id";s:0:"";s:10:"stumble_id";s:0:"";s:9:"flickr_id";s:0:"";s:11:"linkedin_id";s:0:"";s:9:"google_id";s:0:"";s:17:"logo_layout_style";s:7:"onebone";s:16:"show_slider_home";s:4:"true";s:18:"show_slider_single";s:5:"false";s:16:"show_slider_page";s:5:"false";s:19:"show_slider_archive";s:5:"false";s:15:"homepage_layout";s:5:"spage";s:16:"welcome_headline";s:0:"";s:12:"welcome_text";s:0:"";s:18:"left_section_image";s:0:"";s:21:"left_section_headline";s:0:"";s:17:"left_section_text";s:0:"";s:17:"left_section_link";s:0:"";s:20:"center_section_image";s:0:"";s:23:"center_section_headline";s:0:"";s:19:"center_section_text";s:0:"";s:19:"center_section_link";s:0:"";s:19:"right_section_image";s:0:"";s:22:"right_section_headline";s:0:"";s:18:"right_section_text";s:0:"";s:18:"right_section_link";s:0:"";s:22:"show_default_quote_one";s:4:"true";s:18:"quote_section_text";s:0:"";s:18:"quote_section_name";s:0:"";s:14:"show_one_posts";s:4:"true";s:24:"eight_left_section_title";s:0:"";s:23:"eight_left_section_desc";s:0:"";s:25:"eight_left_section_image1";s:0:"";s:25:"eight_left_section_title1";s:0:"";s:24:"eight_left_section_desc1";s:0:"";s:24:"eight_left_section_link1";s:0:"";s:25:"eight_left_section_image2";s:0:"";s:25:"eight_left_section_title2";s:0:"";s:24:"eight_left_section_desc2";s:0:"";s:24:"eight_left_section_link2";s:0:"";s:25:"eight_left_section_image3";s:0:"";s:25:"eight_left_section_title3";s:0:"";s:24:"eight_left_section_desc3";s:0:"";s:24:"eight_left_section_link3";s:0:"";s:26:"eight_middle_section_title";s:0:"";s:22:"eight_portfolio_image1";s:0:"";s:22:"eight_portfolio_image2";s:0:"";s:22:"eight_portfolio_image3";s:0:"";s:22:"eight_portfolio_image4";s:0:"";s:22:"eight_portfolio_image5";s:0:"";s:22:"eight_portfolio_image6";s:0:"";s:22:"eight_portfolio_image7";s:0:"";s:22:"eight_portfolio_image8";s:0:"";s:25:"eight_right_section_title";s:0:"";s:22:"eight_news_section_cat";s:0:"";s:16:"show_posts_eight";s:4:"true";s:19:"show_comments_spage";s:4:"true";s:13:"footer_layout";s:3:"one";}', 'yes'),
(379, 'rewrite_rules', 'a:69:{s:47:"category/(.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:42:"category/(.+?)/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:35:"category/(.+?)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:17:"category/(.+?)/?$";s:35:"index.php?category_name=$matches[1]";s:44:"tag/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:39:"tag/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:32:"tag/([^/]+)/page/?([0-9]{1,})/?$";s:43:"index.php?tag=$matches[1]&paged=$matches[2]";s:14:"tag/([^/]+)/?$";s:25:"index.php?tag=$matches[1]";s:45:"type/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:40:"type/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:33:"type/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?post_format=$matches[1]&paged=$matches[2]";s:15:"type/([^/]+)/?$";s:33:"index.php?post_format=$matches[1]";s:12:"robots\\.txt$";s:18:"index.php?robots=1";s:48:".*wp-(atom|rdf|rss|rss2|feed|commentsrss2)\\.php$";s:18:"index.php?feed=old";s:20:".*wp-app\\.php(/.*)?$";s:19:"index.php?error=403";s:18:".*wp-register.php$";s:23:"index.php?register=true";s:32:"feed/(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:27:"(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:20:"page/?([0-9]{1,})/?$";s:28:"index.php?&paged=$matches[1]";s:27:"comment-page-([0-9]{1,})/?$";s:39:"index.php?&page_id=12&cpage=$matches[1]";s:41:"comments/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:36:"comments/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:44:"search/(.+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:39:"search/(.+)/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:32:"search/(.+)/page/?([0-9]{1,})/?$";s:41:"index.php?s=$matches[1]&paged=$matches[2]";s:14:"search/(.+)/?$";s:23:"index.php?s=$matches[1]";s:47:"author/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:42:"author/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:35:"author/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?author_name=$matches[1]&paged=$matches[2]";s:17:"author/([^/]+)/?$";s:33:"index.php?author_name=$matches[1]";s:69:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:64:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:57:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:81:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&paged=$matches[4]";s:39:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/?$";s:63:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]";s:56:"([0-9]{4})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:51:"([0-9]{4})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:44:"([0-9]{4})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:65:"index.php?year=$matches[1]&monthnum=$matches[2]&paged=$matches[3]";s:26:"([0-9]{4})/([0-9]{1,2})/?$";s:47:"index.php?year=$matches[1]&monthnum=$matches[2]";s:43:"([0-9]{4})/feed/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:38:"([0-9]{4})/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:31:"([0-9]{4})/page/?([0-9]{1,})/?$";s:44:"index.php?year=$matches[1]&paged=$matches[2]";s:13:"([0-9]{4})/?$";s:26:"index.php?year=$matches[1]";s:27:".?.+?/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:37:".?.+?/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:57:".?.+?/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:".?.+?/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:".?.+?/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:20:"(.?.+?)/trackback/?$";s:35:"index.php?pagename=$matches[1]&tb=1";s:40:"(.?.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:35:"(.?.+?)/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:28:"(.?.+?)/page/?([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&paged=$matches[2]";s:35:"(.?.+?)/comment-page-([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&cpage=$matches[2]";s:20:"(.?.+?)(/[0-9]+)?/?$";s:47:"index.php?pagename=$matches[1]&page=$matches[2]";s:27:"[^/]+/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:37:"[^/]+/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:57:"[^/]+/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:"[^/]+/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:"[^/]+/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:20:"([^/]+)/trackback/?$";s:31:"index.php?name=$matches[1]&tb=1";s:40:"([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?name=$matches[1]&feed=$matches[2]";s:35:"([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?name=$matches[1]&feed=$matches[2]";s:28:"([^/]+)/page/?([0-9]{1,})/?$";s:44:"index.php?name=$matches[1]&paged=$matches[2]";s:35:"([^/]+)/comment-page-([0-9]{1,})/?$";s:44:"index.php?name=$matches[1]&cpage=$matches[2]";s:20:"([^/]+)(/[0-9]+)?/?$";s:43:"index.php?name=$matches[1]&page=$matches[2]";s:16:"[^/]+/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:26:"[^/]+/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:46:"[^/]+/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:41:"[^/]+/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:41:"[^/]+/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";}', 'yes'),
(373, '_site_transient_timeout_theme_roots', '1399542770', 'yes'),
(374, '_site_transient_theme_roots', 'a:1:{s:7:"default";s:7:"/themes";}', 'yes'),
(376, '_site_transient_update_themes', 'O:8:"stdClass":4:{s:12:"last_checked";i:1399542129;s:7:"checked";a:1:{s:7:"default";s:3:"1.3";}s:8:"response";a:1:{s:7:"default";a:4:{s:5:"theme";s:7:"default";s:11:"new_version";s:5:"1.7.2";s:3:"url";s:35:"http://wordpress.org/themes/default";s:7:"package";s:54:"http://wordpress.org/themes/download/default.1.7.2.zip";}}s:12:"translations";a:0:{}}', 'yes'),
(335, 'responsive_theme_options', 'a:34:{s:10:"breadcrumb";b:0;s:10:"cta_button";b:0;s:12:"minified_css";b:0;s:10:"front_page";i:1;s:13:"home_headline";N;s:16:"home_subheadline";N;s:17:"home_content_area";N;s:8:"cta_text";N;s:7:"cta_url";N;s:16:"featured_content";N;s:24:"google_site_verification";s:0:"";s:22:"bing_site_verification";s:0:"";s:23:"yahoo_site_verification";s:0:"";s:23:"site_statistics_tracker";s:0:"";s:11:"twitter_uid";s:0:"";s:12:"facebook_uid";s:0:"";s:12:"linkedin_uid";s:0:"";s:11:"youtube_uid";s:0:"";s:11:"stumble_uid";s:0:"";s:7:"rss_uid";s:0:"";s:15:"google_plus_uid";s:0:"";s:13:"instagram_uid";s:0:"";s:13:"pinterest_uid";s:0:"";s:8:"yelp_uid";s:0:"";s:9:"vimeo_uid";s:0:"";s:14:"foursquare_uid";s:0:"";s:21:"responsive_inline_css";s:0:"";s:25:"responsive_inline_js_head";s:0:"";s:31:"responsive_inline_css_js_footer";s:0:"";s:26:"static_page_layout_default";s:7:"default";s:26:"single_post_layout_default";s:7:"default";s:31:"blog_posts_index_layout_default";s:7:"default";s:14:"googleplus_uid";s:0:"";s:15:"stumbleupon_uid";s:0:"";}', 'yes'),
(313, '_transient_timeout_plugin_slugs', '1399562288', 'no'),
(314, '_transient_plugin_slugs', 'a:1:{i:0;s:19:"vslider/vslider.php";}', 'no'),
(356, '_site_transient_timeout_poptags_40cd750bba9870f18aada2478b24840a', '1399475994', 'yes'),
(306, 'db_upgraded', '', 'yes'),
(308, '_site_transient_update_core', 'O:8:"stdClass":4:{s:7:"updates";a:2:{i:0;O:8:"stdClass":10:{s:8:"response";s:6:"latest";s:8:"download";s:62:"http://downloads.wordpress.org/release/ru_RU/wordpress-3.9.zip";s:6:"locale";s:5:"ru_RU";s:8:"packages";O:8:"stdClass":5:{s:4:"full";s:62:"http://downloads.wordpress.org/release/ru_RU/wordpress-3.9.zip";s:10:"no_content";b:0;s:11:"new_bundled";b:0;s:7:"partial";b:0;s:8:"rollback";b:0;}s:7:"current";s:3:"3.9";s:7:"version";s:3:"3.9";s:11:"php_version";s:5:"5.2.4";s:13:"mysql_version";s:3:"5.0";s:11:"new_bundled";s:3:"3.8";s:15:"partial_version";s:0:"";}i:1;O:8:"stdClass":10:{s:8:"response";s:6:"latest";s:8:"download";s:56:"http://downloads.wordpress.org/release/wordpress-3.9.zip";s:6:"locale";s:5:"en_US";s:8:"packages";O:8:"stdClass":5:{s:4:"full";s:56:"http://downloads.wordpress.org/release/wordpress-3.9.zip";s:10:"no_content";b:0;s:11:"new_bundled";b:0;s:7:"partial";b:0;s:8:"rollback";b:0;}s:7:"current";s:3:"3.9";s:7:"version";s:3:"3.9";s:11:"php_version";s:5:"5.2.4";s:13:"mysql_version";s:3:"5.0";s:11:"new_bundled";s:3:"3.8";s:15:"partial_version";s:0:"";}}s:12:"last_checked";i:1399542128;s:15:"version_checked";s:3:"3.9";s:12:"translations";a:0:{}}', 'yes'),
(309, 'can_compress_scripts', '0', 'yes'),
(334, 'theme_mods_responsive', 'a:4:{i:0;b:0;s:12:"header_image";s:73:"http://moneygun.altervista.org/wp-content/uploads/2014/05/cropped-doc.jpg";s:17:"header_image_data";O:8:"stdClass":5:{s:13:"attachment_id";i:76;s:3:"url";s:73:"http://moneygun.altervista.org/wp-content/uploads/2014/05/cropped-doc.jpg";s:13:"thumbnail_url";s:73:"http://moneygun.altervista.org/wp-content/uploads/2014/05/cropped-doc.jpg";s:6:"height";i:100;s:5:"width";i:1240;}s:16:"sidebars_widgets";a:2:{s:4:"time";i:1399453371;s:4:"data";a:5:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:0:{}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}s:9:"sidebar-4";N;}}}', 'yes'),
(350, 'independent_publisher_general_options', 'a:1:{s:20:"show_post_word_count";b:1;}', 'yes'),
(319, 'widget_pages', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(320, 'widget_calendar', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(321, 'widget_tag_cloud', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(322, 'widget_nav_menu', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(357, '_site_transient_poptags_40cd750bba9870f18aada2478b24840a', 'a:40:{s:6:"widget";a:3:{s:4:"name";s:6:"widget";s:4:"slug";s:6:"widget";s:5:"count";s:4:"3898";}s:4:"post";a:3:{s:4:"name";s:4:"Post";s:4:"slug";s:4:"post";s:5:"count";s:4:"2456";}s:6:"plugin";a:3:{s:4:"name";s:6:"plugin";s:4:"slug";s:6:"plugin";s:5:"count";s:4:"2344";}s:5:"admin";a:3:{s:4:"name";s:5:"admin";s:4:"slug";s:5:"admin";s:5:"count";s:4:"1930";}s:5:"posts";a:3:{s:4:"name";s:5:"posts";s:4:"slug";s:5:"posts";s:5:"count";s:4:"1856";}s:7:"sidebar";a:3:{s:4:"name";s:7:"sidebar";s:4:"slug";s:7:"sidebar";s:5:"count";s:4:"1583";}s:7:"twitter";a:3:{s:4:"name";s:7:"twitter";s:4:"slug";s:7:"twitter";s:5:"count";s:4:"1329";}s:6:"google";a:3:{s:4:"name";s:6:"google";s:4:"slug";s:6:"google";s:5:"count";s:4:"1325";}s:8:"comments";a:3:{s:4:"name";s:8:"comments";s:4:"slug";s:8:"comments";s:5:"count";s:4:"1310";}s:6:"images";a:3:{s:4:"name";s:6:"images";s:4:"slug";s:6:"images";s:5:"count";s:4:"1260";}s:4:"page";a:3:{s:4:"name";s:4:"page";s:4:"slug";s:4:"page";s:5:"count";s:4:"1225";}s:5:"image";a:3:{s:4:"name";s:5:"image";s:4:"slug";s:5:"image";s:5:"count";s:4:"1121";}s:9:"shortcode";a:3:{s:4:"name";s:9:"shortcode";s:4:"slug";s:9:"shortcode";s:5:"count";s:4:"1000";}s:8:"facebook";a:3:{s:4:"name";s:8:"Facebook";s:4:"slug";s:8:"facebook";s:5:"count";s:3:"982";}s:5:"links";a:3:{s:4:"name";s:5:"links";s:4:"slug";s:5:"links";s:5:"count";s:3:"974";}s:3:"seo";a:3:{s:4:"name";s:3:"seo";s:4:"slug";s:3:"seo";s:5:"count";s:3:"950";}s:9:"wordpress";a:3:{s:4:"name";s:9:"wordpress";s:4:"slug";s:9:"wordpress";s:5:"count";s:3:"844";}s:7:"gallery";a:3:{s:4:"name";s:7:"gallery";s:4:"slug";s:7:"gallery";s:5:"count";s:3:"821";}s:6:"social";a:3:{s:4:"name";s:6:"social";s:4:"slug";s:6:"social";s:5:"count";s:3:"780";}s:3:"rss";a:3:{s:4:"name";s:3:"rss";s:4:"slug";s:3:"rss";s:5:"count";s:3:"722";}s:7:"widgets";a:3:{s:4:"name";s:7:"widgets";s:4:"slug";s:7:"widgets";s:5:"count";s:3:"686";}s:6:"jquery";a:3:{s:4:"name";s:6:"jquery";s:4:"slug";s:6:"jquery";s:5:"count";s:3:"681";}s:5:"pages";a:3:{s:4:"name";s:5:"pages";s:4:"slug";s:5:"pages";s:5:"count";s:3:"678";}s:5:"email";a:3:{s:4:"name";s:5:"email";s:4:"slug";s:5:"email";s:5:"count";s:3:"623";}s:4:"ajax";a:3:{s:4:"name";s:4:"AJAX";s:4:"slug";s:4:"ajax";s:5:"count";s:3:"615";}s:5:"media";a:3:{s:4:"name";s:5:"media";s:4:"slug";s:5:"media";s:5:"count";s:3:"595";}s:10:"javascript";a:3:{s:4:"name";s:10:"javascript";s:4:"slug";s:10:"javascript";s:5:"count";s:3:"572";}s:5:"video";a:3:{s:4:"name";s:5:"video";s:4:"slug";s:5:"video";s:5:"count";s:3:"570";}s:10:"buddypress";a:3:{s:4:"name";s:10:"buddypress";s:4:"slug";s:10:"buddypress";s:5:"count";s:3:"541";}s:4:"feed";a:3:{s:4:"name";s:4:"feed";s:4:"slug";s:4:"feed";s:5:"count";s:3:"539";}s:7:"content";a:3:{s:4:"name";s:7:"content";s:4:"slug";s:7:"content";s:5:"count";s:3:"530";}s:5:"photo";a:3:{s:4:"name";s:5:"photo";s:4:"slug";s:5:"photo";s:5:"count";s:3:"522";}s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"slug";s:4:"link";s:5:"count";s:3:"506";}s:6:"photos";a:3:{s:4:"name";s:6:"photos";s:4:"slug";s:6:"photos";s:5:"count";s:3:"505";}s:5:"login";a:3:{s:4:"name";s:5:"login";s:4:"slug";s:5:"login";s:5:"count";s:3:"471";}s:4:"spam";a:3:{s:4:"name";s:4:"spam";s:4:"slug";s:4:"spam";s:5:"count";s:3:"458";}s:5:"stats";a:3:{s:4:"name";s:5:"stats";s:4:"slug";s:5:"stats";s:5:"count";s:3:"453";}s:8:"category";a:3:{s:4:"name";s:8:"category";s:4:"slug";s:8:"category";s:5:"count";s:3:"452";}s:7:"youtube";a:3:{s:4:"name";s:7:"youtube";s:4:"slug";s:7:"youtube";s:5:"count";s:3:"436";}s:7:"comment";a:3:{s:4:"name";s:7:"comment";s:4:"slug";s:7:"comment";s:5:"count";s:3:"432";}}', 'yes'),
(352, 'theme_switched_via_customizer', '', 'yes'),
(349, 'theme_mods_independent-publisher', 'a:2:{i:0;b:0;s:16:"sidebars_widgets";a:2:{s:4:"time";i:1399456677;s:4:"data";a:4:{s:19:"wp_inactive_widgets";a:1:{i:0;s:5:"rss-3";}s:9:"sidebar-1";a:0:{}s:18:"orphaned_widgets_1";a:0:{}s:18:"orphaned_widgets_2";a:0:{}}}}', 'yes');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_postmeta`
--

CREATE TABLE IF NOT EXISTS `wp_postmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`meta_id`),
  KEY `post_id` (`post_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=195 ;

--
-- Дамп данных таблицы `wp_postmeta`
--

INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
(59, 12, '_edit_last', '1'),
(60, 12, '_edit_lock', '1399477132:1'),
(61, 12, '_wp_page_template', 'page-templates/front-page.php'),
(62, 14, '_menu_item_type', 'custom'),
(63, 14, '_menu_item_menu_item_parent', '0'),
(64, 14, '_menu_item_object_id', '14'),
(65, 14, '_menu_item_object', 'custom'),
(66, 14, '_menu_item_target', ''),
(67, 14, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(68, 14, '_menu_item_xfn', ''),
(69, 14, '_menu_item_url', 'http://localhost/'),
(71, 15, '_menu_item_type', 'custom'),
(72, 15, '_menu_item_menu_item_parent', '0'),
(73, 15, '_menu_item_object_id', '15'),
(74, 15, '_menu_item_object', 'custom'),
(75, 15, '_menu_item_target', ''),
(76, 15, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(77, 15, '_menu_item_xfn', ''),
(78, 15, '_menu_item_url', 'http://localhost/About'),
(80, 16, '_edit_last', '1'),
(81, 16, '_edit_lock', '1399464792:1'),
(82, 16, '_wp_page_template', 'page-templates/full-width.php'),
(92, 33, '_menu_item_type', 'custom'),
(93, 33, '_menu_item_menu_item_parent', '0'),
(94, 33, '_menu_item_object_id', '33'),
(95, 33, '_menu_item_object', 'custom'),
(96, 33, '_menu_item_target', ''),
(97, 33, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(98, 33, '_menu_item_xfn', ''),
(99, 33, '_menu_item_url', 'http://moneygun.altervista.org/1'),
(101, 34, '_menu_item_type', 'custom'),
(102, 34, '_menu_item_menu_item_parent', '0'),
(103, 34, '_menu_item_object_id', '34'),
(104, 34, '_menu_item_object', 'custom'),
(105, 34, '_menu_item_target', ''),
(106, 34, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(107, 34, '_menu_item_xfn', ''),
(108, 34, '_menu_item_url', 'http://moneygun.altervista.org/2'),
(110, 35, '_menu_item_type', 'custom'),
(111, 35, '_menu_item_menu_item_parent', '0'),
(112, 35, '_menu_item_object_id', '35'),
(113, 35, '_menu_item_object', 'custom'),
(114, 35, '_menu_item_target', ''),
(115, 35, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(116, 35, '_menu_item_xfn', ''),
(117, 35, '_menu_item_url', 'http://moneygun.altervista.org/3'),
(119, 36, '_menu_item_type', 'custom'),
(120, 36, '_menu_item_menu_item_parent', '0'),
(121, 36, '_menu_item_object_id', '36'),
(122, 36, '_menu_item_object', 'custom'),
(123, 36, '_menu_item_target', ''),
(124, 36, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(125, 36, '_menu_item_xfn', ''),
(126, 36, '_menu_item_url', 'http://moneygun.altervista.org/4'),
(128, 37, '_menu_item_type', 'custom'),
(129, 37, '_menu_item_menu_item_parent', '0'),
(130, 37, '_menu_item_object_id', '37'),
(131, 37, '_menu_item_object', 'custom'),
(132, 37, '_menu_item_target', ''),
(133, 37, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(134, 37, '_menu_item_xfn', ''),
(135, 37, '_menu_item_url', 'http://moneygun.altervista.org/5'),
(137, 38, '_menu_item_type', 'custom'),
(138, 38, '_menu_item_menu_item_parent', '0'),
(139, 38, '_menu_item_object_id', '38'),
(140, 38, '_menu_item_object', 'custom'),
(141, 38, '_menu_item_target', ''),
(142, 38, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(143, 38, '_menu_item_xfn', ''),
(144, 38, '_menu_item_url', 'http://moneygun.altervista.org/6'),
(146, 39, '_edit_last', '1'),
(147, 39, '_edit_lock', '1396355793:1'),
(148, 39, '_wp_page_template', 'default'),
(149, 41, '_edit_last', '1'),
(150, 41, '_edit_lock', '1396355800:1'),
(151, 41, '_wp_page_template', 'default'),
(152, 43, '_edit_last', '1'),
(153, 43, '_edit_lock', '1396355806:1'),
(154, 43, '_wp_page_template', 'default'),
(155, 45, '_edit_last', '1'),
(156, 45, '_edit_lock', '1396355811:1'),
(157, 45, '_wp_page_template', 'default'),
(158, 47, '_edit_last', '1'),
(159, 47, '_edit_lock', '1396355817:1'),
(160, 47, '_wp_page_template', 'default'),
(161, 49, '_edit_last', '1'),
(162, 49, '_edit_lock', '1396355831:1'),
(163, 49, '_wp_page_template', 'default'),
(191, 79, '_wp_attached_file', '2014/05/banner_homepage_ownteam.jpg'),
(192, 79, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:1280;s:6:"height";i:375;s:4:"file";s:35:"2014/05/banner_homepage_ownteam.jpg";s:5:"sizes";a:4:{s:9:"thumbnail";a:4:{s:4:"file";s:35:"banner_homepage_ownteam-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:6:"medium";a:4:{s:4:"file";s:34:"banner_homepage_ownteam-300x87.jpg";s:5:"width";i:300;s:6:"height";i:87;s:9:"mime-type";s:10:"image/jpeg";}s:5:"large";a:4:{s:4:"file";s:36:"banner_homepage_ownteam-1024x300.jpg";s:5:"width";i:1024;s:6:"height";i:300;s:9:"mime-type";s:10:"image/jpeg";}s:14:"post-thumbnail";a:4:{s:4:"file";s:35:"banner_homepage_ownteam-624x182.jpg";s:5:"width";i:624;s:6:"height";i:182;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:10:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";}}'),
(193, 80, '_wp_attached_file', '2014/05/banner_homepage_ownteam1.jpg'),
(194, 80, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:1280;s:6:"height";i:375;s:4:"file";s:36:"2014/05/banner_homepage_ownteam1.jpg";s:5:"sizes";a:4:{s:9:"thumbnail";a:4:{s:4:"file";s:36:"banner_homepage_ownteam1-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:6:"medium";a:4:{s:4:"file";s:35:"banner_homepage_ownteam1-300x87.jpg";s:5:"width";i:300;s:6:"height";i:87;s:9:"mime-type";s:10:"image/jpeg";}s:5:"large";a:4:{s:4:"file";s:37:"banner_homepage_ownteam1-1024x300.jpg";s:5:"width";i:1024;s:6:"height";i:300;s:9:"mime-type";s:10:"image/jpeg";}s:14:"post-thumbnail";a:4:{s:4:"file";s:36:"banner_homepage_ownteam1-624x182.jpg";s:5:"width";i:624;s:6:"height";i:182;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:10:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";}}');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_posts`
--

CREATE TABLE IF NOT EXISTS `wp_posts` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext NOT NULL,
  `post_title` text NOT NULL,
  `post_excerpt` text NOT NULL,
  `post_status` varchar(20) NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) NOT NULL DEFAULT 'open',
  `post_password` varchar(20) NOT NULL DEFAULT '',
  `post_name` varchar(200) NOT NULL DEFAULT '',
  `to_ping` text NOT NULL,
  `pinged` text NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext NOT NULL,
  `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `guid` varchar(255) NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT '0',
  `post_type` varchar(20) NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `post_name` (`post_name`),
  KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  KEY `post_parent` (`post_parent`),
  KEY `post_author` (`post_author`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=82 ;

--
-- Дамп данных таблицы `wp_posts`
--

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(12, 1, '2014-04-01 13:43:36', '2014-04-01 09:43:36', '', '', '', 'publish', 'closed', 'closed', '', 'page-1', '', '', '2014-05-07 13:05:54', '2014-05-07 09:05:54', '', 0, 'http://localhost/WP/?page_id=12', 0, 'page', '', 0),
(13, 1, '2014-04-01 13:41:03', '2014-04-01 09:41:03', 'Page 1 Text', 'Page 1', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-04-01 13:41:03', '2014-04-01 09:41:03', '', 12, 'http://localhost/WP/12-revision-v1/', 0, 'revision', '', 0),
(14, 1, '2014-04-01 13:42:46', '2014-04-01 09:42:46', '', 'Home', '', 'publish', 'closed', 'closed', '', 'main', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://localhost/WP/?p=14', 1, 'nav_menu_item', '', 0),
(15, 1, '2014-04-01 13:49:07', '2014-04-01 09:49:07', '', 'About', '', 'publish', 'closed', 'closed', '', 'about-us', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://localhost/WP/?p=15', 2, 'nav_menu_item', '', 0),
(16, 1, '2014-04-01 14:50:50', '2014-04-01 10:50:50', 'Наша компания занимается разработкой сайтов на протяжении 10 лет.', 'О нас', '', 'publish', 'closed', 'closed', '', 'about', '', '', '2014-05-07 15:59:42', '2014-05-07 11:59:42', '', 0, 'http://localhost/WP/?page_id=16', 0, 'page', '', 0),
(17, 1, '2014-04-01 14:50:48', '2014-04-01 10:50:48', 'About Us text', 'About Us', '', 'inherit', 'closed', 'closed', '', '16-revision-v1', '', '', '2014-04-01 14:50:48', '2014-04-01 10:50:48', '', 16, 'http://localhost/WP/16-revision-v1/', 0, 'revision', '', 0),
(18, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Left Section Image', '', 'draft', 'closed', 'closed', '', 'of-left_section_image', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=18', 0, 'optionsframework', '', 0),
(19, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Center Section Image', '', 'draft', 'closed', 'closed', '', 'of-center_section_image', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=19', 0, 'optionsframework', '', 0),
(20, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Right Section Image', '', 'draft', 'closed', 'closed', '', 'of-right_section_image', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=20', 0, 'optionsframework', '', 0),
(21, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Left Section Image1', '', 'draft', 'closed', 'closed', '', 'of-bizeight_left_section_image1', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=21', 0, 'optionsframework', '', 0),
(22, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Left Section Image2', '', 'draft', 'closed', 'closed', '', 'of-bizeight_left_section_image2', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=22', 0, 'optionsframework', '', 0),
(23, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Left Section Image3', '', 'draft', 'closed', 'closed', '', 'of-bizeight_left_section_image3', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=23', 0, 'optionsframework', '', 0),
(24, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image1', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image1', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=24', 0, 'optionsframework', '', 0),
(25, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image2', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image2', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=25', 0, 'optionsframework', '', 0),
(26, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image3', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image3', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=26', 0, 'optionsframework', '', 0),
(27, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image4', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image4', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=27', 0, 'optionsframework', '', 0),
(28, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image5', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image5', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=28', 0, 'optionsframework', '', 0),
(29, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image6', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image6', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=29', 0, 'optionsframework', '', 0),
(30, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image7', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image7', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=30', 0, 'optionsframework', '', 0),
(31, 1, '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 'Bizeight Portfolio Image8', '', 'draft', 'closed', 'closed', '', 'of-bizeight_portfolio_image8', '', '', '2014-04-01 15:09:16', '0000-00-00 00:00:00', '', 0, 'http://localhost/WP/?post_type=optionsframework&p=31', 0, 'optionsframework', '', 0),
(33, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Services', '', 'publish', 'closed', 'closed', '', '1', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=33', 3, 'nav_menu_item', '', 0),
(34, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Expertise', '', 'publish', 'closed', 'closed', '', '2', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=34', 4, 'nav_menu_item', '', 0),
(35, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Clients', '', 'publish', 'closed', 'closed', '', '3', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=35', 5, 'nav_menu_item', '', 0),
(36, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Careers', '', 'publish', 'closed', 'closed', '', '4', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=36', 6, 'nav_menu_item', '', 0),
(37, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Knowledge Center', '', 'publish', 'closed', 'closed', '', '5', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=37', 7, 'nav_menu_item', '', 0),
(38, 1, '2014-04-01 16:37:39', '2014-04-01 12:37:39', '', 'Contact us', '', 'publish', 'closed', 'closed', '', '6', '', '', '2014-04-01 23:17:46', '2014-04-01 19:17:46', '', 0, 'http://nnm-dhimenest/WP/?p=38', 8, 'nav_menu_item', '', 0),
(39, 1, '2014-04-01 16:38:23', '0000-00-00 00:00:00', '1', '1', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:23', '2014-04-01 12:38:23', '', 0, 'http://nnm-dhimenest/WP/?page_id=39', 0, 'page', '', 0),
(40, 1, '2014-04-01 16:38:23', '2014-04-01 12:38:23', '1', '1', '', 'inherit', 'closed', 'closed', '', '39-revision-v1', '', '', '2014-04-01 16:38:23', '2014-04-01 12:38:23', '', 39, 'http://nnm-dhimenest/WP/39-revision-v1/', 0, 'revision', '', 0),
(41, 1, '2014-04-01 16:38:32', '0000-00-00 00:00:00', '2', '2', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:32', '2014-04-01 12:38:32', '', 0, 'http://nnm-dhimenest/WP/?page_id=41', 0, 'page', '', 0),
(42, 1, '2014-04-01 16:38:32', '2014-04-01 12:38:32', '2', '2', '', 'inherit', 'closed', 'closed', '', '41-revision-v1', '', '', '2014-04-01 16:38:32', '2014-04-01 12:38:32', '', 41, 'http://nnm-dhimenest/WP/41-revision-v1/', 0, 'revision', '', 0),
(43, 1, '2014-04-01 16:38:39', '0000-00-00 00:00:00', '3', '3', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:39', '2014-04-01 12:38:39', '', 0, 'http://nnm-dhimenest/WP/?page_id=43', 0, 'page', '', 0),
(44, 1, '2014-04-01 16:38:39', '2014-04-01 12:38:39', '3', '3', '', 'inherit', 'closed', 'closed', '', '43-revision-v1', '', '', '2014-04-01 16:38:39', '2014-04-01 12:38:39', '', 43, 'http://nnm-dhimenest/WP/43-revision-v1/', 0, 'revision', '', 0),
(45, 1, '2014-04-01 16:38:44', '0000-00-00 00:00:00', '4', '4', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:44', '2014-04-01 12:38:44', '', 0, 'http://nnm-dhimenest/WP/?page_id=45', 0, 'page', '', 0),
(46, 1, '2014-04-01 16:38:44', '2014-04-01 12:38:44', '4', '4', '', 'inherit', 'closed', 'closed', '', '45-revision-v1', '', '', '2014-04-01 16:38:44', '2014-04-01 12:38:44', '', 45, 'http://nnm-dhimenest/WP/45-revision-v1/', 0, 'revision', '', 0),
(47, 1, '2014-04-01 16:38:50', '0000-00-00 00:00:00', '5', '5', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:50', '2014-04-01 12:38:50', '', 0, 'http://nnm-dhimenest/WP/?page_id=47', 0, 'page', '', 0),
(48, 1, '2014-04-01 16:38:50', '2014-04-01 12:38:50', '5', '5', '', 'inherit', 'closed', 'closed', '', '47-revision-v1', '', '', '2014-04-01 16:38:50', '2014-04-01 12:38:50', '', 47, 'http://nnm-dhimenest/WP/47-revision-v1/', 0, 'revision', '', 0),
(49, 1, '2014-04-01 16:38:56', '0000-00-00 00:00:00', '6', '6', '', 'draft', 'closed', 'closed', '', '', '', '', '2014-04-01 16:38:56', '2014-04-01 12:38:56', '', 0, 'http://nnm-dhimenest/WP/?page_id=49', 0, 'page', '', 0),
(50, 1, '2014-04-01 16:38:56', '2014-04-01 12:38:56', '6', '6', '', 'inherit', 'closed', 'closed', '', '49-revision-v1', '', '', '2014-04-01 16:38:56', '2014-04-01 12:38:56', '', 49, 'http://nnm-dhimenest/WP/49-revision-v1/', 0, 'revision', '', 0),
(51, 1, '2014-04-01 16:39:41', '2014-04-01 12:39:41', 'Page 1 Text', '', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-04-01 16:39:41', '2014-04-01 12:39:41', '', 12, 'http://nnm-dhimenest/WP/12-revision-v1/', 0, 'revision', '', 0),
(52, 1, '2014-04-01 16:40:16', '2014-04-01 12:40:16', '<h2>Solution Focused Development</h2>\r\nProject Office is a transparent customer-centric development driven organization. This means that we put the solution first and technology second. Project Office''s pool of IT resources is divided into cross-discipline and cross-technology delivery units that develop specific types of solutions. This means that the project manager, developers and quality assurance engineers on your project already have experience developing solutions with similar business and/or technological requirements.', '', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-04-01 16:40:16', '2014-04-01 12:40:16', '', 12, 'http://nnm-dhimenest/WP/12-revision-v1/', 0, 'revision', '', 0),
(55, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Left Section Image1', '', 'draft', 'closed', 'closed', '', 'of-eight_left_section_image1', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=55', 0, 'optionsframework', '', 0),
(56, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Left Section Image2', '', 'draft', 'closed', 'closed', '', 'of-eight_left_section_image2', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=56', 0, 'optionsframework', '', 0),
(57, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Left Section Image3', '', 'draft', 'closed', 'closed', '', 'of-eight_left_section_image3', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=57', 0, 'optionsframework', '', 0),
(58, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image1', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image1', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=58', 0, 'optionsframework', '', 0),
(59, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image2', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image2', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=59', 0, 'optionsframework', '', 0),
(60, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image3', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image3', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=60', 0, 'optionsframework', '', 0),
(61, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image4', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image4', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=61', 0, 'optionsframework', '', 0),
(62, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image5', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image5', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=62', 0, 'optionsframework', '', 0),
(63, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image6', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image6', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=63', 0, 'optionsframework', '', 0),
(64, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image7', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image7', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=64', 0, 'optionsframework', '', 0),
(65, 1, '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 'Eight Portfolio Image8', '', 'draft', 'closed', 'closed', '', 'of-eight_portfolio_image8', '', '', '2014-04-01 23:31:02', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?post_type=optionsframework&p=65', 0, 'optionsframework', '', 0),
(77, 1, '2014-05-07 13:05:36', '2014-05-07 09:05:36', '', 'Main', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-05-07 13:05:36', '2014-05-07 09:05:36', '', 12, 'http://moneygun.altervista.org/12-revision-v1/', 0, 'revision', '', 0),
(78, 1, '2014-05-07 13:05:45', '2014-05-07 09:05:45', '', '', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-05-07 13:05:45', '2014-05-07 09:05:45', '', 12, 'http://moneygun.altervista.org/12-revision-v1/', 0, 'revision', '', 0),
(79, 1, '2014-05-07 19:48:51', '2014-05-07 15:48:51', '', 'banner_homepage_ownteam', '', 'inherit', 'closed', 'closed', '', 'banner_homepage_ownteam', '', '', '2014-05-07 19:48:51', '2014-05-07 15:48:51', '', 0, 'http://moneygun.altervista.org/wp-content/uploads/2014/05/banner_homepage_ownteam.jpg', 0, 'attachment', 'image/jpeg', 0),
(80, 1, '2014-05-07 19:50:07', '2014-05-07 15:50:07', '', 'banner_homepage_ownteam', '', 'inherit', 'closed', 'closed', '', 'banner_homepage_ownteam-2', '', '', '2014-05-07 19:50:07', '2014-05-07 15:50:07', '', 0, 'http://moneygun.altervista.org/wp-content/uploads/2014/05/banner_homepage_ownteam1.jpg', 0, 'attachment', 'image/jpeg', 0),
(81, 1, '2014-05-08 13:44:33', '0000-00-00 00:00:00', '', 'Черновик', '', 'auto-draft', 'closed', 'closed', '', '', '', '', '2014-05-08 13:44:33', '0000-00-00 00:00:00', '', 0, 'http://moneygun.altervista.org/?p=81', 0, 'post', '', 0),
(69, 1, '2014-04-06 18:35:53', '2014-04-06 14:35:53', 'Наша компания занимается разработкой сайтов на протяжении 10 лет.', 'О нас', '', 'inherit', 'closed', 'closed', '', '16-revision-v1', '', '', '2014-04-06 18:35:53', '2014-04-06 14:35:53', '', 16, 'http://moneygun.altervista.org/16-revision-v1/', 0, 'revision', '', 0),
(74, 1, '2014-05-07 12:51:03', '2014-05-07 08:51:03', '', '', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-05-07 12:51:03', '2014-05-07 08:51:03', '', 12, 'http://moneygun.altervista.org/12-revision-v1/', 0, 'revision', '', 0),
(70, 1, '2014-04-06 18:38:51', '2014-04-06 14:38:51', 'Provectus IT является лидером на рынке исследований и разработки программного обеспечения. Наш уникальный комплексный подход позволяет быстро и экономически эффективно создавать инновационные продукты.\r\n\r\nОпираясь на более чем 20 летний опыт и огромный послужной список успешно завершенных проектов с сотнями клиентов, мы предоставляем полный спектр высококачественных ИТ услуг,которые позволяют нашим клиентам с полной отдачей использовать постоянно меняющиеся возможности современного рынка.\r\n\r\nНаш успех определяется, в первую очередь, невероятно талантливой командой, высокой компетентностью и богатым опытом в области разработки программного обеспечения.\r\n\r\nМы можем разрабатывать архитектуру, проектировать, создавать дизайн, тестировать и поддерживать мобильные приложения любой сложности. Наш производственный процесс обеспечивает снижение рисков, затрат и минимизирует время на разработку продукта. Наши услуги включают в себя предварительную оценку, анализ, проектирование, тестирование и дальнейшую поддержку продукта.', '', '', 'inherit', 'closed', 'closed', '', '12-revision-v1', '', '', '2014-04-06 18:38:51', '2014-04-06 14:38:51', '', 12, 'http://moneygun.altervista.org/12-revision-v1/', 0, 'revision', '', 0),
(71, 1, '2014-04-07 23:31:28', '2014-04-07 19:31:28', 'Provectus IT является лидером на рынке исследований и разработки программного обеспечения. Наш уникальный комплексный подход позволяет быстро и экономически эффективно создавать инновационные продукты. Опираясь на более чем 20 летний опыт и огромный послужной список успешно завершенных проектов с сотнями клиентов, мы предоставляем полный спектр высококачественных ИТ услуг,которые позволяют нашим клиентам с полной отдачей использовать постоянно меняющиеся возможности современного рынка. Наш успех определяется, в первую очередь, невероятно талантливой командой, высокой компетентностью и богатым опытом в области разработки программного обеспечения. Мы можем разрабатывать архитектуру, проектировать, создавать дизайн, тестировать и поддерживать мобильные приложения любой сложности. Наш производственный процесс обеспечивает снижение рисков, затрат и минимизирует время на разработку продукта. Наши услуги включают в себя предварительную оценку, анализ, проектирование, тестирование и дальнейшую поддержку продукта.', '', '', 'inherit', 'closed', 'closed', '', '12-autosave-v1', '', '', '2014-04-07 23:31:28', '2014-04-07 19:31:28', '', 12, 'http://moneygun.altervista.org/12-autosave-v1/', 0, 'revision', '', 0);

-- --------------------------------------------------------

--
-- Структура таблицы `wp_terms`
--

CREATE TABLE IF NOT EXISTS `wp_terms` (
  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL DEFAULT '',
  `slug` varchar(200) NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`term_id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

--
-- Дамп данных таблицы `wp_terms`
--

INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Без рубрики', '%d0%b1%d0%b5%d0%b7-%d1%80%d1%83%d0%b1%d1%80%d0%b8%d0%ba%d0%b8', 0),
(2, 'Main menu', 'main-menu', 0),
(3, 'the-langs-group', 'the-langs-group', 0),
(4, 'en_US', 'en_us', 0),
(5, 'ru_RU', 'ru_ru', 0);

-- --------------------------------------------------------

--
-- Структура таблицы `wp_term_relationships`
--

CREATE TABLE IF NOT EXISTS `wp_term_relationships` (
  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_order` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`object_id`,`term_taxonomy_id`),
  KEY `term_taxonomy_id` (`term_taxonomy_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `wp_term_relationships`
--

INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
(14, 2, 0),
(15, 2, 0),
(33, 2, 0),
(34, 2, 0),
(35, 2, 0),
(36, 2, 0),
(37, 2, 0),
(38, 2, 0),
(4, 3, 0),
(5, 3, 0);

-- --------------------------------------------------------

--
-- Структура таблицы `wp_term_taxonomy`
--

CREATE TABLE IF NOT EXISTS `wp_term_taxonomy` (
  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `taxonomy` varchar(32) NOT NULL DEFAULT '',
  `description` longtext NOT NULL,
  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `count` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`term_taxonomy_id`),
  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),
  KEY `taxonomy` (`taxonomy`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

--
-- Дамп данных таблицы `wp_term_taxonomy`
--

INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
(1, 1, 'category', '', 0, 0),
(2, 2, 'nav_menu', '', 0, 8),
(3, 3, 'languages_group', 'the group of languages', 0, 2),
(4, 4, 'language', 'english', 0, 0),
(5, 5, 'language', 'Russian', 0, 0);

-- --------------------------------------------------------

--
-- Структура таблицы `wp_usermeta`
--

CREATE TABLE IF NOT EXISTS `wp_usermeta` (
  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`umeta_id`),
  KEY `user_id` (`user_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=35 ;

--
-- Дамп данных таблицы `wp_usermeta`
--

INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
(1, 1, 'first_name', ''),
(2, 1, 'last_name', ''),
(3, 1, 'nickname', 'dimonze'),
(4, 1, 'description', ''),
(5, 1, 'rich_editing', 'true'),
(6, 1, 'comment_shortcuts', 'false'),
(7, 1, 'admin_color', 'fresh'),
(8, 1, 'use_ssl', '0'),
(9, 1, 'show_admin_bar_front', 'true'),
(10, 1, 'wp_capabilities', 'a:1:{s:13:"administrator";b:1;}'),
(11, 1, 'wp_user_level', '10'),
(12, 1, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media,wp360_revisions,wp360_locks,wp390_widgets,xl-new-version-2-11-3'),
(13, 1, 'show_welcome_panel', '1'),
(14, 1, 'wp_dashboard_quick_press_last_post_id', '81'),
(15, 1, 'managenav-menuscolumnshidden', 'a:4:{i:0;s:11:"link-target";i:1;s:11:"css-classes";i:2;s:3:"xfn";i:3;s:11:"description";}'),
(16, 1, 'metaboxhidden_nav-menus', 'a:3:{i:0;s:8:"add-post";i:1;s:12:"add-post_tag";i:2;s:15:"add-post_format";}'),
(17, 1, 'nav_menu_recently_edited', '2'),
(18, 1, 'closedpostboxes_dashboard', 'a:1:{i:0;s:17:"dashboard_primary";}'),
(19, 1, 'metaboxhidden_dashboard', 'a:0:{}'),
(20, 1, 'wp_user-settings', 'libraryContent=browse&dfw_width=700&imgsize=large&align=none'),
(21, 1, 'wp_user-settings-time', '1399479366'),
(22, 2, 'first_name', 'Vadim'),
(23, 2, 'last_name', 'Updatus'),
(24, 2, 'nickname', 'updatus'),
(25, 2, 'description', ''),
(26, 2, 'rich_editing', 'true'),
(27, 2, 'comment_shortcuts', 'false'),
(28, 2, 'admin_color', 'fresh'),
(29, 2, 'use_ssl', '0'),
(30, 2, 'show_admin_bar_front', 'true'),
(31, 2, 'wp_capabilities', 'a:1:{s:13:"administrator";b:1;}'),
(32, 2, 'wp_user_level', '10'),
(33, 2, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media,wp360_revisions,wp360_locks'),
(34, 2, 'wp_dashboard_quick_press_last_post_id', '68');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_users`
--

CREATE TABLE IF NOT EXISTS `wp_users` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_login` varchar(60) NOT NULL DEFAULT '',
  `user_pass` varchar(64) NOT NULL DEFAULT '',
  `user_nicename` varchar(50) NOT NULL DEFAULT '',
  `user_email` varchar(100) NOT NULL DEFAULT '',
  `user_url` varchar(100) NOT NULL DEFAULT '',
  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_activation_key` varchar(60) NOT NULL DEFAULT '',
  `user_status` int(11) NOT NULL DEFAULT '0',
  `display_name` varchar(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `user_login_key` (`user_login`),
  KEY `user_nicename` (`user_nicename`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

--
-- Дамп данных таблицы `wp_users`
--

INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(1, 'dimonze', '$P$BFJuqQ52IYuTuLnQt.1CtU0m/UoeY61', 'dimonze', 'dimonze@gmail.com', '', '2014-04-01 09:12:54', '', 0, 'dimonze'),
(2, 'updatus', '$P$BZUPXHpSgxM5GwlbEgF3a4VeQdVsyj1', 'updatus', 'updatusvadim@gmail.com', '', '2014-04-02 09:31:11', '', 0, 'Vadim Updatus');

-- --------------------------------------------------------

--
-- Структура таблицы `wp_vslider`
--

CREATE TABLE IF NOT EXISTS `wp_vslider` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `option_name` varchar(255) NOT NULL DEFAULT 'vslider_options',
  `active` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `option_name` (`option_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Дамп данных таблицы `wp_vslider`
--

INSERT INTO `wp_vslider` (`id`, `option_name`, `active`) VALUES
(1, 'vslider_options', 1),
(2, 'mainslider', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
